### ISSUE TITLE
[Feature] Publish dotnet tool

### ISSUE THREAD

**Issue by celluj34** [Vannevelj/directory-packages-props-converter#1]
Hello!

It'd be really neat if we could install this globally as a `dotnet tool`! https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools

Then it could be installed once and used in any project instead of either 1) modifying your PATH, 2) copy/pasting this everywhere you need it, or 3) keeping it only in my download directory.

**Comment by Vannevelj** [comment]
Unless I'm mistaken, a .NET tool needs to be distributed as a nuget package. Since this is written in Rust, that won't be possible. You're right that this means you'll have to do either of the three options you've mentioned; I suppose my expectation is that you'll only use this binary very infrequently: once you run it, you will never need it again for that repo.

Based on that I'll close this as unable to take action, but don't let that stop you from adding to the conversation if there is an aspect I might have missed
